site_name: SARP Documentation
nav:
  - Home: index.md
  - Setup: setup.md
  - Variables: variables.md
  - Examples:
      - Interactive GRD: examples/example1.md
      - Batch SLC: examples/example2.md
      - Snakemake PolSAR: examples/example3.md
  - Troubleshooting: troubleshooting.md
  - Running locally: running_locally.md